name: Build IP lists

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE*"
      - "*.md"
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run:  |
        pip install --upgrade pip
        pip install requests

    - name: Generate country lists
      run: |
        mkdir -p rules
        python scripts/category-ru.py

    - name: Install mihomo
      run: |
        M_VER=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name | sub("^v"; "")')
        echo "Latest mihomo version: $M_VER"
        wget -O mihomo.gz https://github.com/MetaCubeX/mihomo/releases/download/v${M_VER}/mihomo-linux-amd64-v${M_VER}.gz
        gunzip -f mihomo.gz
        chmod +x mihomo
        sudo mv mihomo /usr/local/bin/
        mihomo -v

    - name: Convert .yaml to .mrs
      run: |
        find rules -type f -name "*.yaml" | while read file; do
          mihomo convert-ruleset domain text "$file" "${file%.yaml}.mrs"
        done

    - name: Commit and push generated files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "Rule Set List Generator"
        git config user.email "noreply@myrepo.com"
        git add rules/*
        git commit -m "Update lists" || echo "No changes"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
